# Generated by Django 3.1.2 on 2023-06-27 23:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_carrito_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrito',
            new_name='Cart',
        ),
    ]
